### PR TITLE
Improve instruction

### PR DESCRIPTION
**Pull request by Igmat**
I lost few hours trying to figure out the problem.

Unity website proposes code with spaces in it. It's not a problem for auth apps, but it breaks your action.

I think your code could be adjusted to handle it, but until then it would be nice to address this issue in README.

### CODE REVIEW

**Comment by kuler90** [comment]
Hi @Igmat,

Whitespaces in the code are already handled. I just rerun test action with spaces in the key and everything OK. But I think your PR is good since spaces are just visual separators and Unity can change them to dashes. Thanks!

**Comment by Igmat** [comment]
Good. But, could you please, tell me what's the problem [here](https://github.com/Igmat/ChestReloadedPlugin/blob/master/.github/workflows/main.yml#L68)?
It [failed](https://github.com/Igmat/ChestReloadedPlugin/runs/2171130573?check_suite_focus=true) when there were spaces in my secret `UNITY_AUTHENTICATOR_KEY` and [worked](https://github.com/Igmat/ChestReloadedPlugin/runs/2171395357?check_suite_focus=true) when I updated it.

**Comment by kuler90** [comment]
I don't see any problem in your workflow. Are you sure that just copied key with spaces to secret? All literal spaces are replaced in key before use. Maybe you somehow have some special character spaces in key.

**Comment by Igmat** [comment]
@kuler90 I believe that I just copied it as-is, but I won't recheck again since unity install and activation take quite a long time.
Anyway, it works if spaces are removed:) Btw, thanks very much for your unity actions. IDK how I would automate my flow without it! You're doing great work.

**Comment by kuler90** [comment]
Glad to hear!

**Pull request merged**
